package io.jguardrails.examples;

import io.jguardrails.core.InputRail;
import io.jguardrails.core.OutputRail;
import io.jguardrails.core.RailContext;
import io.jguardrails.core.RailResult;
import io.jguardrails.pipeline.GuardrailPipeline;

/**
 * Example demonstrating how to create custom rails and add them to a pipeline.
 *
 * <p>Shows:</p>
 * <ul>
 *   <li>A custom {@link InputRail} that enforces language restrictions</li>
 *   <li>A custom {@link OutputRail} that appends a legal disclaimer</li>
 * </ul>
 *
 * <p>Run with: {@code ./gradlew :jguardrails-examples:run -PmainClass=io.jguardrails.examples.CustomRailExample}</p>
 */
public class CustomRailExample {

    public static void main(String[] args) {
        System.out.println("=== JGuardrails Custom Rail Example ===\n");

        GuardrailPipeline pipeline = GuardrailPipeline.builder()
                .addInputRail(new LanguageRestrictionRail())
                .addOutputRail(new DisclaimerAppenderRail())
                .blockedResponse("Only English and Russian inputs are accepted.")
                .build();

        RailContext context = RailContext.builder().build();

        // English input — allowed
        System.out.println("--- English input ---");
        String r1 = pipeline.execute("What is machine learning?", context,
                input -> "Machine learning is a subset of AI that enables systems to learn from data.");
        System.out.println("Response: " + r1 + "\n");

        // Russian input — allowed
        System.out.println("--- Russian input ---");
        String r2 = pipeline.execute("Что такое машинное обучение?", context,
                input -> "Машинное обучение — это раздел ИИ.");
        System.out.println("Response: " + r2 + "\n");

        // German input — blocked
        System.out.println("--- German input (blocked) ---");
        String r3 = pipeline.execute("Was ist maschinelles Lernen?", context,
                input -> "This should not be reached.");
        System.out.println("Response: " + r3 + "\n");
    }

    // -------------------------------------------------------------------------
    // Custom InputRail: language restriction
    // -------------------------------------------------------------------------

    /**
     * Custom rail that blocks inputs not in English or Russian.
     * Demonstrates how easy it is to implement a custom {@link InputRail}.
     */
    static class LanguageRestrictionRail implements InputRail {

        @Override
        public String name() { return "language-restriction"; }

        @Override
        public int priority() { return 1; }

        @Override
        public RailResult process(String input, RailContext context) {
            // Simple heuristic: detect Cyrillic for Russian, ASCII for English
            boolean hasCyrillic = input.chars().anyMatch(c -> c >= 0x0400 && c <= 0x04FF);
            boolean isAsciiDominant = input.chars()
                    .filter(c -> c > 31 && c < 128)
                    .count() > input.length() * 0.7;

            if (hasCyrillic || isAsciiDominant) {
                return RailResult.pass(input, name());
            }
            return RailResult.block(name(),
                    "Input language not supported. Only English and Russian are accepted.");
        }
    }

    // -------------------------------------------------------------------------
    // Custom OutputRail: disclaimer appender
    // -------------------------------------------------------------------------

    /**
     * Custom rail that appends a legal disclaimer to every LLM response.
     * Demonstrates how easy it is to implement a custom {@link OutputRail}.
     */
    static class DisclaimerAppenderRail implements OutputRail {

        private static final String DISCLAIMER =
                "\n\n---\n*This response is generated by AI and should not be taken as professional advice.*";

        @Override
        public String name() { return "disclaimer-appender"; }

        @Override
        public int priority() { return 200; }

        @Override
        public RailResult process(String output, String originalInput, RailContext context) {
            String modified = output + DISCLAIMER;
            return RailResult.modify(modified, name(), "Appended legal disclaimer");
        }
    }
}
